# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

markdown: redcarpet

pygments: true

title : Johan's blog site

author :
  name: Johan De Wit
  display_name : Johan De Wit
  email : johan@open-future.be
  web : http://www.open-future.be
  gravatar :
  github : johan-open-future

excerpt_separator : "<!--more-->"

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://johan.open-future.be

